"""Initial combined migration

Revision ID: 1a1281b4eb39
Revises: 
Create Date: 2026-04-10 00:59:20.142648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1281b4eb39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('app_uuid', sa.String(length=36), nullable=False),
    sa.Column('blocked_reason', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklist_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_email'))

    op.drop_table('blacklist')
    # ### end Alembic commands ###
